### PR TITLE
Update python uploader script to listen on TTNv3 MQTT and interpret T…

### PR DESCRIPTION
**Pull request by bertrik**
Script omgebouwd om te luisteren op de MQTT stream van TTNv3 (in plaats van TTNv2).
Ik heb kunnen zien tot zover dat berichtjes herkend worden, maar weet niet of ze ook daadwerkelijk goed in de database terecht komen.

### CODE REVIEW

**Comment by bertrik** [comment]
Let op, dit vervangt het oude script en past het aan voor TTNv3, beter eerst even uitproberen. Niet zomaar mergen, want het vervangt het TTNv2 script.

**Comment by matthijskooijman** [comment]
I slightly modified the content of this PR:
 - Made changes directly to `mjs_mqtt.py`, we'll just run an old checkout in separate clone for v2
 - Reverted changes to filemode
 - Reverted the default app id, no need to add that IMHO (certainly not a change related to v3).
 - Included a commit that adds a `source` field to sensors_message (which is set to ttn.v2 in the initial commit, so we can use that for the v2 version later).
 - Update the source field to ttn.v3 in your commit.
 - Shorten your commit message a bit :-)

I just did a (force!) push with these changes to your branch, and I'm intending to deploy this to our server for further testing (but mysql is still crunching to add the field to the sensors_message table, which is rather huge, so I didn't get around to doing this tonight, hopefully tomorrow).

Before I'm merging this PR,  I do have one more question: Why did you move the decoding of the port and station_id, and pass them separately to `process_data` rather than passing the full `message_payload` as before? I originally thought the v3 format required this, but looking more closely now, I think this could just have stayed the same? Or is your reasoning that now `process_data` only processes data, without having to know about the JSON format at all? I guess that would indeed make sense and be an improvement indeed.

**Comment by bertrik** [comment]
Function process_data() only really uses the binary payload and the payload port. So by passing just those two, all of the TTNv3 specifics are dealt with outside of the process_data() function. This is not essential of course, and it's fine if you revert that

**Comment by matthijskooijman** [comment]
> Function process_data() only really uses the binary payload and the payload port. So by passing just those two, all of the TTNv3 specifics are dealt with outside of the process_data() function. This is not essential of course, and it's fine if you revert that

Right, that's what I gathered, and I agree that this is nicer. I could nitpick and insist that this change goes into its own commit, but let's not and move forward instead. I'm merging this, thanks again!

**Pull request merged**
